/* CREACION USUARIOS */

/* USUARIOS GUEST */
CREATE USER guest1 IDENTIFIED BY guest1;
CREATE USER guest2 IDENTIFIED BY guest2;
CREATE USER guest3 IDENTIFIED BY guest3;

/* USUARIOS MESAS */
CREATE USER mesas1 IDENTIFIED BY mesas1;
CREATE USER mesas2 IDENTIFIED BY mesas2;
CREATE USER mesas3 IDENTIFIED BY mesas3;
CREATE USER mesas4 IDENTIFIED BY mesas4;

/* USUARIOS IT */
CREATE USER it1 IDENTIFIED BY it1;
CREATE USER it2 IDENTIFIED BY it2;
CREATE USER it3 IDENTIFIED BY it3;

/* USUARIOS ADMIN */
CREATE USER admin1 IDENTIFIED BY admin1;
CREATE USER admin2 IDENTIFIED BY admin2;

CREATE USER dani3l8200 IDENTIFIED BY dani3l8200;
/* CREACION ROLES */
CREATE ROLE GUEST;
CREATE ROLE MESAS;
CREATE ROLE IT;
CREATE ROLE ADMIN;
SELECT * FROM  DBA_ROLES;
/* ROL DE GUEST */
GRANT SELECT ON ELECCIONES.DEPARTAMENTO TO GUEST;
GRANT SELECT ON ELECCIONES.MUNICIPIO TO GUEST;
GRANT SELECT ON ELECCIONES.PARTIDO TO GUEST;
GRANT SELECT ON ELECCIONES.ELECCION TO GUEST;
GRANT SELECT ON ELECCIONES.ACTA TO GUEST;
GRANT SELECT ON ELECCIONES.VOTO TO GUEST;
GRANT CREATE ANY VIEW, CONNECT TO GUEST;
/* ROL DE MESAS */
GRANT SELECT ON ELECCIONES.DEPARTAMENTO TO MESAS;
GRANT SELECT ON ELECCIONES.MUNICIPIO TO MESAS;
GRANT SELECT ON ELECCIONES.PARTIDO TO MESAS;
GRANT SELECT ON ELECCIONES.ELECCION TO MESAS;
GRANT SELECT ON ELECCIONES.ACTA TO MESAS;
GRANT SELECT ON ELECCIONES.VOTO TO MESAS;
GRANT INSERT ON ELECCIONES.DEPARTAMENTO TO MESAS;
GRANT INSERT ON ELECCIONES.MUNICIPIO TO MESAS;
GRANT INSERT ON ELECCIONES.PARTIDO TO MESAS;
GRANT INSERT ON ELECCIONES.ELECCION TO MESAS;
GRANT INSERT ON ELECCIONES.ACTA TO MESAS;
GRANT INSERT ON ELECCIONES.VOTO TO MESAS;
GRANT CONNECT TO MESAS;
/* ROL DE IT */
GRANT SELECT ON ELECCIONES.DEPARTAMENTO TO IT;
GRANT SELECT ON ELECCIONES.MUNICIPIO TO IT;
GRANT SELECT ON ELECCIONES.PARTIDO TO IT;
GRANT SELECT ON ELECCIONES.ELECCION TO IT;
GRANT SELECT ON ELECCIONES.ACTA TO IT;
GRANT SELECT ON ELECCIONES.VOTO TO IT;
GRANT CREATE ANY TABLE, CREATE ANY INDEX, CREATE USER, CONNECT TO IT;
/* ROL DE ADMIN */
GRANT UPDATE ON ELECCIONES.DEPARTAMENTO TO ADMIN;
GRANT UPDATE ON ELECCIONES.MUNICIPIO TO ADMIN;
GRANT UPDATE ON ELECCIONES.PARTIDO TO ADMIN;
GRANT UPDATE ON ELECCIONES.ELECCION TO ADMIN;
GRANT UPDATE ON ELECCIONES.ACTA TO ADMIN;
GRANT UPDATE ON ELECCIONES.VOTO TO ADMIN;
GRANT INSERT ON ELECCIONES.DEPARTAMENTO TO ADMIN;
GRANT INSERT ON ELECCIONES.MUNICIPIO TO ADMIN;
GRANT INSERT ON ELECCIONES.PARTIDO TO ADMIN;
GRANT INSERT ON ELECCIONES.ELECCION TO ADMIN;
GRANT INSERT ON ELECCIONES.ACTA TO ADMIN;
GRANT INSERT ON ELECCIONES.VOTO TO ADMIN;
GRANT SELECT ON ELECCIONES.DEPARTAMENTO TO ADMIN;
GRANT SELECT ON ELECCIONES.MUNICIPIO TO ADMIN;
GRANT SELECT ON ELECCIONES.PARTIDO TO ADMIN;
GRANT SELECT ON ELECCIONES.ELECCION TO ADMIN;
GRANT SELECT ON ELECCIONES.ACTA TO ADMIN;
GRANT SELECT ON ELECCIONES.VOTO TO ADMIN;
GRANT DELETE ON ELECCIONES.DEPARTAMENTO TO ADMIN;
GRANT DELETE ON ELECCIONES.MUNICIPIO TO ADMIN;
GRANT DELETE ON ELECCIONES.PARTIDO TO ADMIN;
GRANT DELETE ON ELECCIONES.ELECCION TO ADMIN;
GRANT DELETE ON ELECCIONES.ACTA TO ADMIN;
GRANT DELETE ON ELECCIONES.VOTO TO ADMIN;
GRANT CREATE USER, CONNECT TO ADMIN;

/* ASIGNACION ROLES A USUARIOS */ 
GRANT GUEST TO guest1, guest2, guest3;
GRANT MESAS TO mesas1, mesas2, mesas3, mesas4;
GRANT IT TO it1, it2, it3;
GRANT ADMIN TO admin1, admin2;

-- drop user guest1, guest2, guest3, mesas1, mesas2, mesas3, mesas4, it1, it2, it3, admin1, admin2;