/* CREACION USUARIOS */

/* USUARIOS GUEST */
CREATE USER guest1 IDENTIFIED BY guest1;
CREATE USER guest2 IDENTIFIED BY guest2;
CREATE USER guest3 IDENTIFIED BY guest3;

/* USUARIOS MESAS */
CREATE USER mesas1 IDENTIFIED BY mesas1;
CREATE USER mesas2 IDENTIFIED BY mesas2;
CREATE USER mesas3 IDENTIFIED BY mesas3;
CREATE USER mesas4 IDENTIFIED BY mesas4;

/* USUARIOS IT */
CREATE USER it1 IDENTIFIED BY it1;
CREATE USER it2 IDENTIFIED BY it2;
CREATE USER it3 IDENTIFIED BY it3;

/* USUARIOS ADMIN */
CREATE USER admin1 IDENTIFIED BY admin1;
CREATE USER admin2 IDENTIFIED BY admin2;


/* CREACION ROLES */
CREATE ROLE GUEST;
CREATE ROLE MESAS;
CREATE ROLE IT;
CREATE ROLE ADMIN;

DROP ROLE GUEST;
DROP ROLE MESAS;
DROP ROLE IT;
DROP ROLE ADMIN;

COLUMN ROLE FORMAT A12
COLUMN ID FORMAT 999
COLUMN COMMON FORMAT A6
COLUMN INHERITED FORMAT A6
COLUMN IMPLICIT FORMAT A6
SELECT ROLE, ROLE_ID ID, COMMON, INHERITED, IMPLICIT FROM  DBA_ROLES WHERE ROLE IN ('GUEST', 'MESAS', 'ADMIN','IT');
/* ROL DE GUEST */
GRANT SELECT ON ELECCIONES.DEPARTAMENTO TO GUEST;
GRANT SELECT ON ELECCIONES.MUNICIPIO TO GUEST;
GRANT SELECT ON ELECCIONES.PARTIDO TO GUEST;
GRANT SELECT ON ELECCIONES.ELECCION TO GUEST;
GRANT SELECT ON ELECCIONES.ACTA TO GUEST;
GRANT SELECT ON ELECCIONES.VOTO TO GUEST;
GRANT CONNECT TO GUEST;

GRANT SELECT ON ELECCIONES.DEPARTAMENTO TO GUEST1;
GRANT SELECT ON ELECCIONES.MUNICIPIO TO GUEST1;
GRANT SELECT ON ELECCIONES.PARTIDO TO GUEST1;
GRANT SELECT ON ELECCIONES.ELECCION TO GUEST1;
GRANT SELECT ON ELECCIONES.ACTA TO GUEST1;
GRANT SELECT ON ELECCIONES.VOTO TO GUEST1;
GRANT CREATE VIEW TO GUEST1;

/* ROL DE MESAS */
GRANT SELECT ON ELECCIONES.DEPARTAMENTO TO MESAS;
GRANT SELECT ON ELECCIONES.MUNICIPIO TO MESAS;
GRANT SELECT ON ELECCIONES.PARTIDO TO MESAS;
GRANT SELECT ON ELECCIONES.ELECCION TO MESAS;
GRANT SELECT ON ELECCIONES.ACTA TO MESAS;
GRANT SELECT ON ELECCIONES.VOTO TO MESAS;
GRANT INSERT ON ELECCIONES.DEPARTAMENTO TO MESAS;
GRANT INSERT ON ELECCIONES.MUNICIPIO TO MESAS;
GRANT INSERT ON ELECCIONES.PARTIDO TO MESAS;
GRANT INSERT ON ELECCIONES.ELECCION TO MESAS;
GRANT INSERT ON ELECCIONES.ACTA TO MESAS;
GRANT INSERT ON ELECCIONES.VOTO TO MESAS;
GRANT CONNECT TO MESAS;
/* ROL DE IT */
GRANT SELECT ON ELECCIONES.DEPARTAMENTO TO IT;
GRANT SELECT ON ELECCIONES.MUNICIPIO TO IT;
GRANT SELECT ON ELECCIONES.PARTIDO TO IT;
GRANT SELECT ON ELECCIONES.ELECCION TO IT;
GRANT SELECT ON ELECCIONES.ACTA TO IT;
GRANT SELECT ON ELECCIONES.VOTO TO IT;
GRANT CREATE ANY TABLE, CREATE ANY INDEX, CREATE USER, CONNECT TO IT;
/* ROL DE ADMIN */
GRANT UPDATE ON ELECCIONES.DEPARTAMENTO TO ADMIN;
GRANT UPDATE ON ELECCIONES.MUNICIPIO TO ADMIN;
GRANT UPDATE ON ELECCIONES.PARTIDO TO ADMIN;
GRANT UPDATE ON ELECCIONES.ELECCION TO ADMIN;
GRANT UPDATE ON ELECCIONES.ACTA TO ADMIN;
GRANT UPDATE ON ELECCIONES.VOTO TO ADMIN;
GRANT INSERT ON ELECCIONES.DEPARTAMENTO TO ADMIN;
GRANT INSERT ON ELECCIONES.MUNICIPIO TO ADMIN;
GRANT INSERT ON ELECCIONES.PARTIDO TO ADMIN;
GRANT INSERT ON ELECCIONES.ELECCION TO ADMIN;
GRANT INSERT ON ELECCIONES.ACTA TO ADMIN;
GRANT INSERT ON ELECCIONES.VOTO TO ADMIN;
GRANT SELECT ON ELECCIONES.DEPARTAMENTO TO ADMIN;
GRANT SELECT ON ELECCIONES.MUNICIPIO TO ADMIN;
GRANT SELECT ON ELECCIONES.PARTIDO TO ADMIN;
GRANT SELECT ON ELECCIONES.ELECCION TO ADMIN;
GRANT SELECT ON ELECCIONES.ACTA TO ADMIN;
GRANT SELECT ON ELECCIONES.VOTO TO ADMIN;
GRANT DELETE ON ELECCIONES.DEPARTAMENTO TO ADMIN;
GRANT DELETE ON ELECCIONES.MUNICIPIO TO ADMIN;
GRANT DELETE ON ELECCIONES.PARTIDO TO ADMIN;
GRANT DELETE ON ELECCIONES.ELECCION TO ADMIN;
GRANT DELETE ON ELECCIONES.ACTA TO ADMIN;
GRANT DELETE ON ELECCIONES.VOTO TO ADMIN;
GRANT CREATE USER, CONNECT TO ADMIN;


SELECT * FROM DBA_ROLE_PRIVS;
/* ASIGNACION ROLES A USUARIOS */ 
GRANT GUEST TO guest1, guest2, guest3;
GRANT MESAS TO mesas1, mesas2, mesas3, mesas4;
GRANT IT TO it1, it2, it3;
GRANT ADMIN TO admin1, admin2;

COLUMN GRANTEE FORMAT A12
COLUMN GRANTED_ROLE FORMAT A10
COLUMN ADMIN_OPTION FORMAT A5
COLUMN INHERITED FORMAT A5
SELECT GRANTEE, GRANTED_ROLE, ADMIN_OPTION, DEFAULT_ROLE, INHERITED FROM DBA_ROLE_PRIVS WHERE granted_role IN ('IT','ADMIN','MESAS','GUEST') ORDER BY GRANTEE;

drop user guest1 cascade;
drop user guest2 cascade;
drop user guest3 cascade;
drop user mesas1;
drop user mesas2;
drop user mesas3;
drop user mesas4;
drop user it1;
drop user it2;
drop user it3;
drop user admin1;
drop user admin2;