------------------------------------------------------------ TABLESPACE CREATION ------------------------------------------------------------
SET ECHO OFF
SET TERMOUT OFF
SET FEEDBACK ON
SET PAGESIZE 32766
SET LINESIZE 32766
SET MARKUP HTML OFF
SET HEADING ON
CREATE TABLESPACE ELECCIONESTBS 
    DATAFILE '/bbdd/practica/tablespaces/ELECCIONESDTF.tbs' SIZE 250M 
        AUTOEXTEND ON NEXT 250M MAXSIZE 500M;
SELECT TABLESPACE_NAME, BLOCK_SIZE, INITIAL_EXTENT, MAX_EXTENTS, STATUS, CONTENTS, ALLOCATION_TYPE FROM DBA_TABLESPACES;        
COLUMN LOCATION_FILE FORMAT A50
COLUMN NAME FORMAT A15
COLUMN "TAMANIO MB" FORMAT 9999.99
COLUMN "MAX_SIZE MB" FORMAT 99999.99
SELECT TABLESPACE_NAME NAME, FILE_NAME LOCATION_FILE,FILE_ID ID,BLOCKS, STATUS,(BYTES/1024)/1024 "TAMANIO MB", (MAXBYTES/1024)/1024 "MAX_SIZE MB" FROM DBA_DATA_FILES;

-- DROP TABLESPACE ELECCIONESTBS INCLUDING CONTENTS AND DATAFILES;

--------------------------------------------------------------- CREATION SCHEMA ---------------------------------------------------------------
CREATE USER ELECCIONES IDENTIFIED BY elecciones 
DEFAULT TABLESPACE ELECCIONESTBS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON ELECCIONESTBS;

GRANT CONNECT, RESOURCE TO ELECCIONES;

COLUMN USERNAME FORMAT A15
COLUMN USER_ID FORMAT 9999
COLUMN STATUS FORMAT A10
COLUMN DEFAULT_TABLESPACE FORMAT A13
COLUMN CREATED FORMAT A10
COLUMN EXPIRY_DATE FORMAT A10
SELECT USERNAME, USER_ID, ACCOUNT_STATUS STATUS, DEFAULT_TABLESPACE, CREATED, EXPIRY_DATE FROM DBA_USERS WHERE USERNAME='ELECCIONES';

-- DROP USER ELECCIONES CASCADE;

COLUMN TNAME FORMAT A15
COLUMN TABTYPE FORMAT A15