------------------------------------------------------------ TABLESPACE CREATION ------------------------------------------------------------
CREATE TABLESPACE ELECCIONESTBS 
    DATAFILE '/bbdd/practica/tablespaces/ELECCIONESDTF.tbs' SIZE 250M 
        AUTOEXTEND ON NEXT 250M MAXSIZE 500M;

SELECT FILE_NAME LOCATION_FILE, TABLESPACE_NAME NAME,(BYTES/1024)/1024 "TAMANIO MB", (MAXBYTES/1024)/1024 "MAX_SIZE MB" FROM DBA_DATA_FILES;

-- DROP TABLESPACE ELECCIONESTBS INCLUDING CONTENTS AND DATAFILES;

--------------------------------------------------------------- CREATION SCHEMA ---------------------------------------------------------------
CREATE USER ELECCIONES IDENTIFIED BY elecciones 
DEFAULT TABLESPACE ELECCIONESTBS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON ELECCIONESTBS;

GRANT CONNECT, RESOURCE TO ELECCIONES;

SELECT * FROM DBA_USERS WHERE USERNAME='ELECCIONES';

-- DROP USER ELECCIONES CASCADE;
